name: autograding

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install package dependencies
      run: npm install

    - name: Create test build
      run: npm run build

    - name: Execute test cases
      run: npm test